CREATEDB todo IF NOT EXISTS;

CREATE TABLE todo IF NOT EXISTS(
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT false
);

